name: CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GIT_COMMITTER_NAME: GitHub
  GIT_COMMITTER_EMAIL: noreply@github.com

jobs:
  test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: version
        with:
          file: test/fixtures/version.txt
          prepend: test
      - name: Print outputs
        run: |
          echo ${{ steps.version.outputs.version }}
          echo ${{ steps.version.outputs.major }}
          echo ${{ steps.version.outputs.minor }}
          echo ${{ steps.version.outputs.patch }}

  cd:
    name: Validate and Release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: make

      - name: Version
        id: version
        uses: ./

      - name: Create Release ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.version.outputs.version }} \
            --title ${{ steps.version.outputs.version }} \
            --target ${{ github.sha }}

      - name: Checkout ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.version.outputs.version }}
          fetch-depth: 0

      # https://github.com/actions/toolkit/blob/master/docs/action-versioning.md
      - name: Tag and Push v${{ steps.version.outputs.major }}
        if: github.event_name == 'push'
        run: |
          git tag -fa v${{ steps.version.outputs.major }} -m "Update v${{ steps.version.outputs.major }} tag"
          git push origin v${{ steps.version.outputs.major }} --force
