name: CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: version
        with:
          file: test/fixtures/version.txt
          prepend: test
      - name: Print outputs
        run: |
          echo ${{ steps.version.outputs.version }}
          echo ${{ steps.version.outputs.major }}
          echo ${{ steps.version.outputs.minor }}
          echo ${{ steps.version.outputs.patch }}

  cd:
    name: Validate and Release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: make

      - name: Version
        id: version
        uses: ./

      - name: Create Release ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}

      - name: Checkout ${{ steps.version.outputs.version }}
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.version.outputs.version }}
          fetch-depth: 0

      - name: Tag and Push v${{ steps.version.outputs.major }}
        if: github.event_name == 'push'
        run: |
          git tag -f v${{ steps.version.outputs.major }}
          git push -f origin v${{ steps.version.outputs.major }}
